project:
  type: website
  output-dir: 'docs'

website:
  title: "In Class Quarto Test 11-21-22"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

